package et.com.smpp.model;
// Generated Aug 20, 2019 2:50:16 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BulkMessage generated by hbm2java
 */
@Entity
@Table(name="bulkMessage"
    ,catalog="smppSmsDb"
)
public class BulkMessage  implements java.io.Serializable {


     private Long id;
     private String phoneNumber;
     private String messageBody;
     private Date sentTime;
     private boolean sentStatus;
     private boolean send;

    public BulkMessage() {
    }

	
    public BulkMessage(Date sentTime, boolean sentStatus, boolean send) {
        this.sentTime = sentTime;
        this.sentStatus = sentStatus;
        this.send = send;
    }
    public BulkMessage(String phoneNumber, String messageBody, Date sentTime, boolean sentStatus, boolean send) {
       this.phoneNumber = phoneNumber;
       this.messageBody = messageBody;
       this.sentTime = sentTime;
       this.sentStatus = sentStatus;
       this.send = send;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="phoneNumber")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="messageBody", length=65535)
    public String getMessageBody() {
        return this.messageBody;
    }
    
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sentTime", nullable=false, length=19)
    public Date getSentTime() {
        return this.sentTime;
    }
    
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }

    
    @Column(name="sentStatus", nullable=false)
    public boolean isSentStatus() {
        return this.sentStatus;
    }
    
    public void setSentStatus(boolean sentStatus) {
        this.sentStatus = sentStatus;
    }

    
    @Column(name="send", nullable=false)
    public boolean isSend() {
        return this.send;
    }
    
    public void setSend(boolean send) {
        this.send = send;
    }




}


