package et.com.smpp.model;
// Generated Aug 20, 2019 2:50:16 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessageTable generated by hbm2java
 */
@Entity
@Table(name="messageTable"
    ,catalog="smppSmsDb"
)
public class MessageTable  implements java.io.Serializable {


     private Long id;
     private CatagoryTable catagoryTable;
     private String message;
     private Date currDate;

    public MessageTable() {
    }

	
    public MessageTable(CatagoryTable catagoryTable, Date currDate) {
        this.catagoryTable = catagoryTable;
        this.currDate = currDate;
    }
    public MessageTable(CatagoryTable catagoryTable, String message, Date currDate) {
       this.catagoryTable = catagoryTable;
       this.message = message;
       this.currDate = currDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="catagoryId", nullable=false)
    public CatagoryTable getCatagoryTable() {
        return this.catagoryTable;
    }
    
    public void setCatagoryTable(CatagoryTable catagoryTable) {
        this.catagoryTable = catagoryTable;
    }

    
    @Column(name="message")
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="currDate", nullable=false, length=19)
    public Date getCurrDate() {
        return this.currDate;
    }
    
    public void setCurrDate(Date currDate) {
        this.currDate = currDate;
    }




}


