package et.com.smpp.model;
// Generated Aug 20, 2019 2:50:16 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NamedParameterList generated by hbm2java
 */
@Entity
@Table(name="NamedParameterList"
    ,catalog="smppSmsDb"
)
public class NamedParameterList  implements java.io.Serializable {


     private Long id;
     private String itemkey;
     private String value;
     private long syncOrderRelationDumpId;

    public NamedParameterList() {
    }

	
    public NamedParameterList(long syncOrderRelationDumpId) {
        this.syncOrderRelationDumpId = syncOrderRelationDumpId;
    }
    public NamedParameterList(String itemkey, String value, long syncOrderRelationDumpId) {
       this.itemkey = itemkey;
       this.value = value;
       this.syncOrderRelationDumpId = syncOrderRelationDumpId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="itemkey", length=1024)
    public String getItemkey() {
        return this.itemkey;
    }
    
    public void setItemkey(String itemkey) {
        this.itemkey = itemkey;
    }

    
    @Column(name="value", length=1024)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="SyncOrderRelationDump_id", nullable=false)
    public long getSyncOrderRelationDumpId() {
        return this.syncOrderRelationDumpId;
    }
    
    public void setSyncOrderRelationDumpId(long syncOrderRelationDumpId) {
        this.syncOrderRelationDumpId = syncOrderRelationDumpId;
    }




}


