package et.com.smpp.model;
// Generated Aug 20, 2019 2:50:16 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Passwordhistory generated by hbm2java
 */
@Entity
@Table(name="passwordhistory"
    ,catalog="smppSmsDb"
)
public class Passwordhistory  implements java.io.Serializable {


     private Long id;
     private String password;
     private long staffId;
     private Date createdOn;

    public Passwordhistory() {
    }

	
    public Passwordhistory(long staffId, Date createdOn) {
        this.staffId = staffId;
        this.createdOn = createdOn;
    }
    public Passwordhistory(String password, long staffId, Date createdOn) {
       this.password = password;
       this.staffId = staffId;
       this.createdOn = createdOn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="password", length=200)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="staffId", nullable=false)
    public long getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(long staffId) {
        this.staffId = staffId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn", nullable=false, length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }




}


