package et.com.smpp.model;
// Generated Aug 20, 2019 2:50:16 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubscribtionTable generated by hbm2java
 */
@Entity
@Table(name="subscribtionTable"
    ,catalog="smppSmsDb"
)
public class SubscribtionTable  implements java.io.Serializable {


     private Long id;
     private CatagoryTable catagoryTable;
     private String phoneNumber;
     private Date currDate;
     private boolean status;
     private String reciever;

    public SubscribtionTable() {
    }

	
    public SubscribtionTable(CatagoryTable catagoryTable, Date currDate, boolean status) {
        this.catagoryTable = catagoryTable;
        this.currDate = currDate;
        this.status = status;
    }
    public SubscribtionTable(CatagoryTable catagoryTable, String phoneNumber, Date currDate, boolean status, String reciever) {
       this.catagoryTable = catagoryTable;
       this.phoneNumber = phoneNumber;
       this.currDate = currDate;
       this.status = status;
       this.reciever = reciever;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="catagoryId", nullable=false)
    public CatagoryTable getCatagoryTable() {
        return this.catagoryTable;
    }
    
    public void setCatagoryTable(CatagoryTable catagoryTable) {
        this.catagoryTable = catagoryTable;
    }

    
    @Column(name="phoneNumber")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="currDate", nullable=false, length=19)
    public Date getCurrDate() {
        return this.currDate;
    }
    
    public void setCurrDate(Date currDate) {
        this.currDate = currDate;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="reciever")
    public String getReciever() {
        return this.reciever;
    }
    
    public void setReciever(String reciever) {
        this.reciever = reciever;
    }




}


