package et.com.smpp.model;
// Generated Aug 20, 2019 2:50:16 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SyncOrderRelationDump generated by hbm2java
 */
@Entity
@Table(name="SyncOrderRelationDump"
    ,catalog="smppSmsDb"
)
public class SyncOrderRelationDump  implements java.io.Serializable {


     private Long id;
     private String effectiveTime;
     private String expiryTime;
     private String productId;
     private String serviceId;
     private String serviceList;
     private String spId;
     private Integer type;
     private String updateDesc;
     private String updateTime;
     private Integer updateType;
     private String userId;

    public SyncOrderRelationDump() {
    }

    public SyncOrderRelationDump(String effectiveTime, String expiryTime, String productId, String serviceId, String serviceList, String spId, Integer type, String updateDesc, String updateTime, Integer updateType, String userId) {
       this.effectiveTime = effectiveTime;
       this.expiryTime = expiryTime;
       this.productId = productId;
       this.serviceId = serviceId;
       this.serviceList = serviceList;
       this.spId = spId;
       this.type = type;
       this.updateDesc = updateDesc;
       this.updateTime = updateTime;
       this.updateType = updateType;
       this.userId = userId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="effectiveTime", length=1024)
    public String getEffectiveTime() {
        return this.effectiveTime;
    }
    
    public void setEffectiveTime(String effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    
    @Column(name="expiryTime", length=1024)
    public String getExpiryTime() {
        return this.expiryTime;
    }
    
    public void setExpiryTime(String expiryTime) {
        this.expiryTime = expiryTime;
    }

    
    @Column(name="productID", length=1024)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="serviceID", length=1024)
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    
    @Column(name="serviceList", length=1024)
    public String getServiceList() {
        return this.serviceList;
    }
    
    public void setServiceList(String serviceList) {
        this.serviceList = serviceList;
    }

    
    @Column(name="spID", length=1024)
    public String getSpId() {
        return this.spId;
    }
    
    public void setSpId(String spId) {
        this.spId = spId;
    }

    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    
    @Column(name="updateDesc", length=1024)
    public String getUpdateDesc() {
        return this.updateDesc;
    }
    
    public void setUpdateDesc(String updateDesc) {
        this.updateDesc = updateDesc;
    }

    
    @Column(name="updateTime", length=1024)
    public String getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    
    @Column(name="updateType")
    public Integer getUpdateType() {
        return this.updateType;
    }
    
    public void setUpdateType(Integer updateType) {
        this.updateType = updateType;
    }

    
    @Column(name="userId", length=1024)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }




}


